### ISSUE TITLE
 How do I add the Start and Stop buttons??

### ISSUE THREAD

**Issue by steve-koo** [Divine1/sliderproject#1]
source update please!!

**Comment by Divine1** [comment]
Hi @steve-koo ,

i have added start and stop buttons.
i have release this as a npm package. 
You can find the installation instructions [here ](https://www.npmjs.com/package/vue-slider-rw)

And of course i have updated the [source code](https://github.com/Divine1/sliderproject.git) in my git repository too. 

i have added more details in the documentation and let me know if you face any issues.

**Comment by steve-koo** [comment]
I am really grateful for your request.
I will use the updated source very gratefully.
Thank you again!!

**Comment by Divine1** [comment]
Hi @steve-koo 
Wonderful. let me know if you need any modifications. 
Takecare

**Comment by steve-koo** [comment]
hi @Divine1 
I'm sorry I keep asking.
Can you give each slideDuration as the source below?
Your source has always been a great force for me.
Thank you very much!
------------------------------------------------------------------
images : [
        {
          id: 0,
          url : "/images/image1.jpg",
          title: "Lightning",
		  slideDuration : 1000
        },
        {
          id: 1,
          url : "/images/image2.jpg",
          title: "Batman on the roof",
		  slideDuration : 5000
        },
        {
          id: 2,
          url : "/images/image3.jpg",
          title: "Suicide Squad",
		  slideDuration : 2000
        },
        {
          id: 3,
          url : "/images/image4.jpg",
          title: "Flash & Reverse Flash",
		  slideDuration : 3000
        },
        {
          id: 4,
          url : "/images/image5.jpg",
          title: "Batman Red",
		  slideDuration : 1000
        }
      ],
------------------------------------------------------------------
