### ISSUE TITLE
can you give each slideDuration as the source below?

### ISSUE THREAD

**Issue by steve-koo** [Divine1/sliderproject#2]
hi @Divine1 
I'm sorry I keep asking.
Can you give each slideDuration as the source below?
Your source has always been a great force for me.
Thank you very much!

------------------------------------------------------------------
images : [
        {
          id: 0,
          url : "/images/image1.jpg",
          title: "Lightning",
		  slideDuration : 1000
        },
        {
          id: 1,
          url : "/images/image2.jpg",
          title: "Batman on the roof",
		  slideDuration : 5000
        },
        {
          id: 2,
          url : "/images/image3.jpg",
          title: "Suicide Squad",
		  slideDuration : 2000
        },
        {
          id: 3,
          url : "/images/image4.jpg",
          title: "Flash & Reverse Flash",
		  slideDuration : 3000
        },
        {
          id: 4,
          url : "/images/image5.jpg",
          title: "Batman Red",
		  slideDuration : 1000
        }
      ],
------------------------------------------------------------------

**Comment by Divine1** [comment]
hi @steve-koo ,
This is a good idea. But, to include this feature i have to change many things on the current code flow and also include new wrapper classes. So this has to be a separate project.
i will try to do this as a separate project when i find time and let you know.

**Comment by steve-koo** [comment]
hi @Divine1 
Thanks for meeting my request.
I hope you can confirm with a new project as soon as possible.
If you have time to spare, ask to create a quick project.
Thank you every day and have a good day.
